resources:
    App\Entity\Review:
        attributes:
            normalization_context:
                groups: ['review:read']
            denormalization_context:
                groups: ['review:write']
            order:
                createdAt: 'DESC'
        iri: http://schema.org/Review
        properties:
            rate:
                iri: https://schema.org/reviewRating
            review:
                iri: http://schema.org/reviewBody
            book:
                iri: http://schema.org/itemReviewed
            author:
                iri: iri="http://schema.org/author
        itemOperations:
            get: ~
            put: ~